import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Provider } from "./provider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} relative bg-bgColor`}
        suppressHydrationWarning={true}
      >
        <Provider>
          <div className="z-10 relative min-h-screen">{children}</div>
          <Image
            src="/vectors.svg"
            alt="Vercel Logo"
            className="w-full absolute bottom-0 left-0 object-contain object-bottom z-[1]"
            width={100}
            height={24}
            priority
          />
        </Provider>
        <ToastContainer autoClose={3000} />
      </body>
    </html>
  );
}
